kind: pipeline
type: docker
name: Test

platform:
  os: linux
  arch: arm64

steps:
- name: Fetch tags
  image: drone/git
  commands:
  - git fetch --tags
- name: Lint
  image: python:3.6-alpine
  commands:
  - apk update && apk add gcc libc-dev
  - pip install --upgrade pip pylint
  - pip install -r requirements.txt
  - pylint templategen
#- name: Test
#  image: python:3.6-alpine
#  - apk update && apk add git
#  - pip install --upgrade pip setuptools wheel
#  - pip install .
- name: Publish PyPi
  image: python:3.6-alpine
  environment:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_token
  commands:
  - apk update && apk add git gcc libc-dev libffi-dev
  - pip install --upgrade pip setuptools wheel twine
  - ./setup.py sdist
  - twine upload dist/* --username="${username}" --password="${password}"
#- name: Publish PyPi
#  image: plugins/pypi
#  settings:
#    username:
#      from_secret: pypi_username
#    password:
#      from_secret: pypi_token
